---
- name: Setup app stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup variables
      include_vars: vars/output_vars

    - name: Import DevOps setup variables
      include_vars: vars/appstack

    - name: Create vprofile ec2 key
      ec2_key:
        name: appstack
        region: "{{region}}"
      register: appstack_out

    - name: Save private key into file ansibleappstack-key.pem
      copy:
        content: "{{appstack_out.key.private_key}}"
        dest: "./ansibleappstack_key.pem"
        mode: 0600
      when: appstack_out.changed
  

