- hosts: localhost
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: Create VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout 

#    - debug:
#       var: vpcout

    - name: Create public subnet 1 in zone 1
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PubSub1Cidr}}"
        region: "{{region}}"
        az : "{{zone1}}"
        map_public : yes
        tags:
          Name: ansible-pubsub1
      register: pubsub1_out

    - name: Create public subnet 2 in zone 2
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PubSub2Cidr}}"
        region: "{{region}}"
        az : "{{zone2}}"
        map_public : yes
        tags:
          Name: ansible-pubsub2
      register: pubsub2_out  

    - name: Create public subnet 3 in zone 3
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PubSub3Cidr}}"
        region: "{{region}}"
        az : "{{zone3}}"
        map_public : yes
        tags:
          Name: ansible-pubsub3
      register: pubsub3_out          

    - name: Create private subnet 1 in zone 1
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PrivSub1Cidr}}"
        region: "{{region}}"
        az : "{{zone1}}"
        map_public : yes
        tags:
          Name: ansible-privsub1
      register: privsub1_out
      
    - name: Create private subnet 2 in zone 2
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PrivSub2Cidr}}"
        region: "{{region}}"
        az : "{{zone2}}"
        map_public : yes
        tags:
          Name: ansible-privsub2
      register: privsub2_out 

    - name: Create private subnet 3 in zone 3
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PrivSub3Cidr}}"
        region: "{{region}}"
        az : "{{zone3}}"
        map_public : yes
        tags:
          Name: ansible-privsub3
      register: privsub3_out

    - name: Create Internet gateway with tags
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        state: "{{state}}"
        region: "{{region}}"
        tags:
            Name: ansible_igw
      register: igw_out

    - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: Ansible-PublicRT
        subnets:
          - "{{ pubsub1_out.subnet.id }}"
          - "{{ pubsub2_out.subnet.id }}"
          - "{{ pubsub3_out.subnet_id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_out.gateway_id }}"
      register: pubRT_out 